spring.application.name=jobAluguelComunicacao
server.port=8090

# Configurações WAHA
waha.enabled=true
waha.base-url=http://100.72.175.86:3050
waha.session=default
waha.intervalo-envio-ms=4000
waha.welcome-message=Ol\u00E1! Seja muito bem-vindo(a) \u00E0 Job Imobiliaria. \uD83C\uDFE1\u2728\n\n\u00C9 um grande prazer ter voc\u00EA aqui. Sabemos que buscar um novo lar ou um bom investimento \u00E9 um passo muito importante, e a nossa equipe est\u00E1 pronta para tornar essa jornada simples, segura e transparente para voc\u00EA.\n\nComo podemos te ajudar a encontrar o im\u00F3vel ideal em Formosa e regi\u00E3o hoje?
waha.menu-principal-text=Para direcionar o seu atendimento rapidamente ao setor correto, por favor, digite o n\u00FAmero da op\u00E7\u00E3o desejada:\n\n1\uFE0F\u20E3 - Quero comprar um im\u00F3vel\n2\uFE0F\u20E3 - Quero alugar um im\u00F3vel\n3\uFE0F\u20E3 - Quero anunciar meu im\u00F3vel\n4\uFE0F\u20E3 - Financeiro / 2\u00AA via de boleto\n5\uFE0F\u20E3 - Outras d\u00FAvidas / Falar com um corretor\n\nDigite apenas o n\u00FAmero e j\u00E1 vamos te atender!
waha.api-key=DistectiWahaAutomation@

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/job_imobiliaria_homologacao
spring.datasource.username=postgres
spring.datasource.password=abacate@post
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect