spring.application.name=jobAluguelComunicacao
server.port=8090

# Configurações WAHA
waha.enabled=true
waha.base-url=http://100.72.175.86:3050
waha.session=default
waha.intervalo-envio-ms=2000
waha.api-key=DistectiWahaAutomation@

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/job_imobiliaria_homologacao
spring.datasource.username=postgres
spring.datasource.password=abacate@post
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect